# Generated by Django 3.1.5 on 2021-01-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210116_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zoom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
